import type { EvaluationResult } from './types';

export function resultToMarkdown(
  idea: string,
  successCriteria: string,
  result: EvaluationResult,
): string {
  const lines: string[] = [];

  lines.push('# /1> Ship Check');
  lines.push('');
  lines.push('## Idea');
  lines.push(idea.trim());
  lines.push('');
  lines.push('## Success Criteria');
  lines.push(successCriteria.trim());
  lines.push('');
  lines.push('## Idea Summary');
  lines.push(result.summary);
  lines.push('');
  lines.push(`## Clarity Review (${result.clarityReview.score}/5)`);
  if (result.clarityReview.comment) lines.push(result.clarityReview.comment);
  lines.push('');
  lines.push(`## MVP Scope (${result.mvpScope.score}/5)`);
  if (result.mvpScope.comment) lines.push(result.mvpScope.comment);
  if (result.mvpScope.shouldCut.length > 0) {
    lines.push('');
    lines.push('**줄여야 할 것**');
    for (const item of result.mvpScope.shouldCut) lines.push(`- ${item}`);
  }
  lines.push('');
  lines.push('## First Feature');
  lines.push(`**${result.firstFeature.title}**`);
  lines.push('');
  lines.push(result.firstFeature.description);
  lines.push('');
  lines.push('## Success Metric');
  lines.push(result.improvedSuccessMetric);
  lines.push('');
  if (result.risks.length > 0) {
    lines.push('## Risk / Caution');
    for (const item of result.risks) lines.push(`- ${item}`);
    lines.push('');
  }
  if (result.nextActions.length > 0) {
    lines.push('## Next Action');
    result.nextActions.forEach((item, i) => lines.push(`${i + 1}. ${item}`));
    lines.push('');
  }
  lines.push('---');
  lines.push('Generated by /1> Ship Check — idea2ship');

  return lines.join('\n');
}
