import type { EvaluationResult } from './types';

export function resultToMarkdown(
  idea: string,
  successCriteria: string,
  result: EvaluationResult,
): string {
  const { shipType, confidence, scores, mvpStrategy, nextActions } = result;
  const lines: string[] = [];

  lines.push('# /1> Ship Check');
  lines.push('');
  lines.push(`**Ship Type**: ${shipType.name} · ${shipType.nameEn}`);
  lines.push(`**신뢰도**: ${confidence}/100`);
  if (shipType.canShipInWeek) {
    lines.push(`> ✅ Can Ship in 1 Week — ${shipType.blurb}`);
  } else if (shipType.blurb) {
    lines.push(`> ${shipType.blurb}`);
  }
  lines.push('');

  lines.push('## Idea');
  lines.push(idea.trim());
  lines.push('');
  lines.push('## Success Metric');
  lines.push(successCriteria.trim());
  lines.push('');

  lines.push('## Summary');
  lines.push(result.summary);
  lines.push('');

  lines.push('## Scores');
  lines.push(`- 명확성 Clarity: ${scores.clarity}/5`);
  lines.push(`- MVP 범위 Scope: ${scores.mvpScope}/5`);
  lines.push(`- 실행 가능성 Feasibility: ${scores.feasibility}/5`);
  lines.push('');

  if (mvpStrategy.keep.length > 0 || mvpStrategy.cut.length > 0) {
    lines.push('## 이번 주 MVP');
    if (mvpStrategy.keep.length > 0) {
      lines.push('**Keep**');
      for (const item of mvpStrategy.keep) lines.push(`- ${item}`);
    }
    if (mvpStrategy.cut.length > 0) {
      lines.push('');
      lines.push('**Cut**');
      for (const item of mvpStrategy.cut) lines.push(`- ~~${item}~~`);
    }
    lines.push('');
  }

  if (nextActions.length > 0) {
    lines.push('## 다음 행동');
    nextActions.forEach((item, i) => lines.push(`${i + 1}. ${item}`));
    lines.push('');
  }

  lines.push('---');
  lines.push('Generated by /1> Ship Check — idea2ship.xyz');

  return lines.join('\n');
}
